appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: QLDsJ3TptB5JeEoRRetUkZ/GGzrBv0mxZdGIRHJOgvFeFdjVD1xYXNvzoYzrVtNHA8R6asWw02q4Cv/kELpC9F564hj9Vf7I3m0dFpSLaOEeALVJhBNW8Hmi01NHrlwJqdUib8+tV0CqecjSWmoFCGFJm8bu4Qve6fid+7qcj1jzw9b7vq8odZeqgu7ENHTZezosyY2umE9JjEbIgaupZmxOOaNpn80InGTdIyjhBfcRMeeG3Mba7RRCWZOV24UpUayMK271sJ09tpH2HLooS3q30GkZFEbhOkmGk6PAyKVQQxAg+gr+oc4Ug2M97G8SkhpTo+Y5mLcN9BJpR6U1WjIYHECRC9QIKG7H2vRx5F6nSoopBeR6pIeFBRUnb4z7uJudRgunXKXbZosDPz5zlnqlDzXuH7/8kwR754cKmBqrS5MM9RkDzhZdVhOHdrQQqYiqiCDN9MBIQ1aQRa4c9Ht/Qy6m+eRKIcD+JWKVv4hi+UpKcI9Yb1alT/OG4jG1jYZJM1HDdkZIF4BIXWtJ9tSbXxIzuCex6pGtYRCy+//frI3gH5gcFlUo73Y5zoGXzRQhStlEkVtHdoZ948KrA016mVpdJoNNTHmMygVPXydowe3XLmj4U0Hemm/RdBSwVXj96TaRaJmbXVdsQMKWT19Am702tfWkyxKRhHYpWg8=}
bot:
  automerge: true
